apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-busybox-agrocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ParagShahade/app-argocd.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp

  syncPolicy:
    syncOptions:
    - CreateNamspace=true
    
    automated:
      selfHeal: true
      prune: true